/**
 * sync-agent-views — canonical vault → Claude/Cursor generated views.
 * Contract: docs/specs/2026-07-18-sync-agent-views-contract.md
 *
 * v1: rules → .claude/.cursor (one-way). memory → MCP feed only (native memory is agent-owned).
 */

import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  readdirSync,
  renameSync,
} from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { parseFrontmatter } from './frontmatter.mjs';

export const GENERATED_MARKER = 'luna:generated by scripts/sync-agent-views.mjs';

/** HTML comment only — used for Claude rules (auto-loaded; no visible heading noise). */
export const GENERATED_COMMENT = `<!-- ${GENERATED_MARKER} — DO NOT EDIT; edit rules/<name>.md -->\n`;

/** Comment + visible heading — Cursor .mdc (not auto-injected the same way). */
export const GENERATED_BANNER =
  GENERATED_COMMENT + `# GENERATED — edit the canonical source (rules/), not this file\n\n`;

const PROTECTED_NAMES = new Set([
  'lessons.md',
  'lessons.mdc',
  'RULES.md',
  'RULES.mdc',
  'luna.mdc',
]);

export function isProtectedName(name) {
  const base = basename(name);
  if (PROTECTED_NAMES.has(base)) return true;
  if (/\.local\.(md|mdc)$/i.test(base)) return true;
  return false;
}

export function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export function hasGeneratedMarker(text) {
  return (
    text.includes(GENERATED_MARKER) ||
    text.includes('"_luna_generated": "scripts/sync-agent-views.mjs"') ||
    text.includes('"_luna_generated":"scripts/sync-agent-views.mjs"')
  );
}

export function manifestPath(projectRoot) {
  return join(projectRoot, '.luna', 'agent-views-manifest.json');
}

export function loadManifest(projectRoot) {
  const path = manifestPath(projectRoot);
  if (!existsSync(path)) return { version: 1, updated: null, targets: {} };
  try {
    const data = JSON.parse(readFileSync(path, 'utf8'));
    if (!data.targets) data.targets = {};
    return data;
  } catch (err) {
    throw new Error(`sync-agent-views: corrupt manifest ${path}: ${err.message}`);
  }
}

export function saveManifest(projectRoot, manifest) {
  const path = manifestPath(projectRoot);
  mkdirSync(join(projectRoot, '.luna'), { recursive: true });
  const next = {
    version: 1,
    updated: new Date().toISOString(),
    targets: manifest.targets || {},
  };
  const tmp = `${path}.${process.pid}.tmp`;
  writeFileSync(tmp, JSON.stringify(next, null, 2) + '\n', 'utf8');
  renameSync(tmp, path);
  return path;
}

function listMd(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && !isProtectedName(f))
    .sort();
}

function cursorDescription(name, body) {
  const first = body.split('\n').find((l) => l.startsWith('# '));
  const title = first ? first.replace(/^#\s+/, '').trim() : name;
  return `Luna Agent Kit — ${title}`.replace(/"/g, "'");
}

/** Claude rules: HTML comment only (no # GENERATED heading — context noise). */
export function renderClaudeRule(sourceBody) {
  return GENERATED_COMMENT + '\n' + sourceBody.replace(/^\uFEFF/, '').replace(/^\n+/, '');
}

export function renderCursorRule(name, sourceBody) {
  const body = sourceBody.replace(/^\uFEFF/, '').replace(/^\n+/, '');
  const front =
    `---\n` +
    `description: ${cursorDescription(name, body)}\n` +
    `alwaysApply: true\n` +
    `---\n\n`;
  return front + GENERATED_BANNER + body;
}

/**
 * Build sync plan. Native Claude memory is NOT a write target (agent-owned).
 */
export function buildPlan(projectRoot) {
  const root = resolve(projectRoot);
  const rulesDir = join(root, 'rules');
  const memoryDir = join(root, 'memory');
  const writes = [];
  const skipped = [];
  const plannedPaths = new Set();

  for (const file of listMd(rulesDir)) {
    const sourcePath = join(rulesDir, file);
    const body = readFileSync(sourcePath, 'utf8');
    const name = file.replace(/\.md$/, '');

    const claudePath = join(root, '.claude', 'rules', file);
    const cursorPath = join(root, '.cursor', 'rules', `${name}.mdc`);

    writes.push({
      path: claudePath,
      source: relative(root, sourcePath),
      desired: renderClaudeRule(body),
      kind: 'claude-rule',
    });
    writes.push({
      path: cursorPath,
      source: relative(root, sourcePath),
      desired: renderCursorRule(name, body),
      kind: 'cursor-rule',
    });
    plannedPaths.add(claudePath);
    plannedPaths.add(cursorPath);
  }

  for (const p of ['lessons.md', 'RULES.md']) {
    if (existsSync(join(rulesDir, p))) {
      skipped.push({ path: join(rulesDir, p), reason: 'protected-source-ignored' });
    }
  }

  // memory → MCP feed only (never native ~/.claude/projects/.../memory)
  const memFiles = listMd(memoryDir);
  const indexEntries = [];
  for (const file of memFiles) {
    const sourcePath = join(memoryDir, file);
    const text = readFileSync(sourcePath, 'utf8');
    const { data, body } = parseFrontmatter(text);
    const title = data.title ? String(data.title) : basename(file, '.md');
    const summary = body.replace(/\s+/g, ' ').trim().slice(0, 120);
    indexEntries.push({ file, title, summary });
  }

  const feedPath = join(root, 'docs', 'generated', 'mcp-memory-feed.json');
  const feed = {
    _luna_generated: 'scripts/sync-agent-views.mjs',
    schema_version: 1,
    project: basename(root),
    memories: indexEntries.map((e) => ({
      file: `memory/${e.file}`,
      title: e.title,
      summary: e.summary,
    })),
  };
  writes.push({
    path: feedPath,
    source: 'memory/*',
    desired: JSON.stringify(feed, null, 2) + '\n',
    kind: 'mcp-feed',
  });
  plannedPaths.add(feedPath);

  return { root, writes, skipped, plannedPaths };
}

/**
 * Orphans: manifest targets we previously wrote that are no longer in the plan
 * (canonical source deleted). Warn only in v1 — do not auto-delete.
 */
export function findOrphans(plan, manifest) {
  const orphans = [];
  for (const [path, meta] of Object.entries(manifest.targets || {})) {
    if (plan.plannedPaths.has(path)) continue;
    if (isProtectedName(path)) continue;
    orphans.push({ path, source: meta.source, kind: meta.kind });
  }
  return orphans;
}

function unifiedDiff(path, current, desired) {
  const a = (current || '').split('\n');
  const b = (desired || '').split('\n');
  const lines = [`--- ${path} (current)`, `+++ ${path} (desired)`];
  const max = Math.max(a.length, b.length);
  let shown = 0;
  for (let i = 0; i < max && shown < 80; i++) {
    if (a[i] === b[i]) continue;
    if (a[i] !== undefined) {
      lines.push(`- ${a[i]}`);
      shown++;
    }
    if (b[i] !== undefined) {
      lines.push(`+ ${b[i]}`);
      shown++;
    }
  }
  if (lines.length === 2) lines.push('(no line-level delta captured)');
  return lines.join('\n');
}

/**
 * Classify planned writes.
 * - marked + no manifest → adopt + regenerate (fresh clone / CI)
 * - marked + manifest hash mismatch → abort (local edit)
 * - unmarked → abort (hand-authored)
 */
export function classifyPlan(plan, manifest) {
  const noop = [];
  const write = [];
  const conflicts = [];
  const adopts = [];

  for (const item of plan.writes) {
    if (isProtectedName(item.path)) {
      conflicts.push({ path: item.path, reason: 'protected-target' });
      continue;
    }

    if (!existsSync(item.path)) {
      write.push(item);
      continue;
    }

    const current = readFileSync(item.path, 'utf8');
    if (current === item.desired) {
      noop.push(item);
      continue;
    }

    const marked = hasGeneratedMarker(current);
    const prev = manifest.targets?.[item.path];
    const currentHash = sha256(current);

    if (!marked) {
      conflicts.push({
        path: item.path,
        reason: 'hand-authored-no-marker',
        current,
        desired: item.desired,
      });
      continue;
    }

    if (!prev) {
      // Fresh clone / missing manifest: trust the marker, regenerate.
      write.push(item);
      adopts.push(item.path);
      continue;
    }

    if (prev.sha256 === currentHash) {
      write.push(item);
      continue;
    }

    conflicts.push({
      path: item.path,
      reason: 'local-modifications',
      current,
      desired: item.desired,
    });
  }

  return { noop, write, conflicts, adopts };
}

export function formatConflicts(conflicts) {
  return conflicts
    .map((c) => {
      const head = `CONFLICT ${c.path}\n  reason: ${c.reason}`;
      if (c.current !== undefined && c.desired !== undefined) {
        return `${head}\n${unifiedDiff(c.path, c.current, c.desired)}`;
      }
      return head;
    })
    .join('\n\n');
}

export function applyWrites(projectRoot, items, manifest) {
  const targets = { ...(manifest.targets || {}) };
  for (const item of items) {
    mkdirSync(dirname(item.path), { recursive: true });
    writeFileSync(item.path, item.desired, 'utf8');
    targets[item.path] = {
      sha256: sha256(item.desired),
      source: item.source,
      kind: item.kind,
      updated: new Date().toISOString(),
    };
  }
  // Drop orphan entries from manifest when their source is gone (keep file warn-only)
  const planned = new Set(items.map((i) => i.path));
  // Also keep entries for noop paths still in plan — caller merges after full classify
  return { targets, planned };
}

export function syncAgentViews(projectRoot, opts = {}) {
  const root = resolve(projectRoot);
  const plan = buildPlan(root);
  const manifest = loadManifest(root);
  const classified = classifyPlan(plan, manifest);
  const orphans = findOrphans(plan, manifest);

  if (classified.conflicts.length) {
    return {
      status: 'conflict',
      exitCode: 2,
      plan,
      classified,
      orphans,
      message: formatConflicts(classified.conflicts),
    };
  }

  if (opts.check || opts.dryRun) {
    const dirty = classified.write.length > 0;
    const adoptNote = classified.adopts?.length
      ? `; would adopt ${classified.adopts.length} marked-no-manifest`
      : '';
    const orphanNote = orphans.length ? `; orphans=${orphans.length}` : '';
    return {
      status: dirty ? 'check-dirty' : 'ok',
      exitCode: dirty ? 1 : 0,
      plan,
      classified,
      orphans,
      message: dirty
        ? `would write ${classified.write.length} file(s); noop=${classified.noop.length}${adoptNote}${orphanNote}`
        : `up to date (noop=${classified.noop.length})${orphanNote}`,
    };
  }

  // Persist full plan paths in manifest (writes + noops that still exist)
  const targets = { ...(manifest.targets || {}) };
  for (const item of [...classified.write, ...classified.noop]) {
    if (classified.write.includes(item)) {
      mkdirSync(dirname(item.path), { recursive: true });
      writeFileSync(item.path, item.desired, 'utf8');
    }
    targets[item.path] = {
      sha256: sha256(item.desired),
      source: item.source,
      kind: item.kind,
      updated: new Date().toISOString(),
    };
  }
  // Remove orphan keys from manifest (files left on disk with a warn)
  for (const o of orphans) {
    delete targets[o.path];
  }
  saveManifest(root, { targets });

  const adoptNote = classified.adopts?.length
    ? `; adopted ${classified.adopts.length} marked-no-manifest`
    : '';
  const orphanNote = orphans.length
    ? `; WARN ${orphans.length} orphan(s) (canonical deleted — generated copy left on disk)`
    : '';

  return {
    status: 'ok',
    exitCode: 0,
    plan,
    classified,
    orphans,
    message: `wrote ${classified.write.length}; noop ${classified.noop.length}${adoptNote}${orphanNote}`,
  };
}
