/**
 * Shared leaf utilities (T13 consolidation).
 *
 * Single home for helpers that were duplicated across libs: content hashing,
 * the generated-view marker, the knowledge-exclusion filter, the date stamp, and
 * relative-path normalization. Import from here instead of re-defining.
 * This module imports nothing local (leaf) to avoid dependency cycles.
 */
import { createHash } from 'node:crypto';

/** Marker written into generated agent views (was defined in agent-views.mjs). */
export const GENERATED_MARKER = 'luna:generated by scripts/sync-agent-views.mjs';

/**
 * sha256 hex of text (null/undefined coerced to ''). Matches the former
 * graph-memory/context-pack/vault-gateway `sha256Text`.
 * @param {string} text
 */
export function sha256Text(text) {
  return createHash('sha256').update(String(text ?? ''), 'utf8').digest('hex');
}

/** UTC date stamp `YYYY-MM-DD`. */
export function today() {
  return new Date().toISOString().slice(0, 10);
}

/** Normalize a relative path: backslashes → '/', strip leading slashes. */
export function normalizeRelPath(path) {
  return String(path || '').replace(/\\/g, '/').replace(/^\/+/, '');
}

/**
 * True if a path/excerpt is a generated mirror or archive that must be excluded
 * from the canonical knowledge corpus (dedupe + graph-memory). Keeps the protected
 * `lessons.md` checkable. Was duplicated as isExcludedGraphSource / isExcludedPath.
 * @param {string} path
 * @param {string} [excerpt]
 */
export function isExcludedKnowledgePath(path, excerpt = '') {
  const norm = normalizeRelPath(path);
  if (!norm) return true;
  if (
    norm.startsWith('docs/generated/') ||
    norm.includes('/_archive/') ||
    norm.startsWith('docs/_archive/')
  ) {
    return true;
  }
  if (norm.startsWith('.cursor/rules/')) return true;
  if (norm.startsWith('.claude/rules/')) {
    if (norm === '.claude/rules/lessons.md') return false;
    return true;
  }
  const body = String(excerpt || '');
  if (body.includes(GENERATED_MARKER) || body.includes('# GENERATED — edit the canonical')) {
    return true;
  }
  return false;
}
