/**
 * Studio-facing re-export of the vault gateway (keeps actions import path stable).
 * Implementation: scripts/lib/vault-gateway.mjs
 */
export {
  assertVaultId,
  assertBodySize,
  assertCtxAllowed,
  normalizeError,
  MAX_BODY_BYTES,
  summarizeSyncResult,
  planTokenFromSummary,
  vaultCreate,
  vaultUpdate,
  vaultDelete,
  vaultMerge,
  vaultRead,
  vaultReadSha,
  vaultList,
  vaultWikilinks,
  vaultSyncPreview,
  vaultSyncPreviewMany,
  vaultSyncApply,
  vaultSyncApplyMany,
  vaultLifecyclePreview,
  vaultLifecycleApply,
  vaultDedupeReport,
  vaultGraphMemoryStatus,
  vaultGraphMemorySearch,
  vaultGraphMemoryRebuild,
  vaultGraphMemoryTool,
  vaultContextPackPreview,
  vaultContextPackBuild,
  vaultContextPackDrift,
  vaultCorrectionCandidates,
  vaultCorrectionAccept,
  vaultCorrectionReject,
  vaultReuseSearch,
  vaultAdrDecisions,
  listSyncTargets,
} from "../../.plugin/scripts/lib/vault-gateway.mjs";
