#!/usr/bin/env node
/**
 * Obsidian export — Phase 5 (T16) hermetic tests.
 * Design: docs/specs/2026-07-22-obsidian-vault-export.md.
 */
import assert from 'node:assert/strict';
import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
  mkdtempSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { join, relative } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { exportObsidianVault, visibleExportPath, EXPORT_REL } from '../../scripts/lib/obsidian-export.mjs';

let failed = 0;
function test(name, fn) {
  try {
    fn();
    console.log(`  ok  ${name}`);
  } catch (e) {
    failed++;
    console.error(`  FAIL ${name}`);
    console.error(e);
  }
}

function sha8(s) {
  return createHash('sha256').update(String(s)).digest('hex').slice(0, 8);
}

function listFiles(dir, base = dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) listFiles(p, base, out);
    else out.push(relative(base, p).replace(/\\/g, '/'));
  }
  return out;
}

function makeVault() {
  const root = mkdtempSync(join(tmpdir(), 'luna-obs-'));
  const id = `vault-obs-${sha8(root)}`;
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  mkdirSync(join(root, 'rules'), { recursive: true });
  mkdirSync(join(root, 'memory'), { recursive: true });
  mkdirSync(join(root, '.claude', 'rules'), { recursive: true });
  mkdirSync(join(root, '.cursor', 'rules'), { recursive: true });
  mkdirSync(join(root, 'docs', 'generated'), { recursive: true });

  writeFileSync(join(root, 'docs', 'specs', 'auth.md'), '---\ntitle: Auth\n---\n\n# Auth\n\nSee [[core]].\n');
  writeFileSync(join(root, 'rules', 'core.md'), '# Core\n\nUser wins.\n');
  writeFileSync(join(root, 'memory', 'note.md'), '---\ntitle: Note\n---\n\n# Note\n');
  writeFileSync(join(root, '.claude', 'rules', 'lessons.md'), '- AVOID x — DO y (2026-01-01)\n');
  // generated mirror — must be excluded
  writeFileSync(join(root, '.claude', 'rules', 'core.md'), '<!-- luna:generated by scripts/sync-agent-views.mjs -->\ngenerated\n');
  writeFileSync(join(root, '.cursor', 'rules', 'core.mdc'), 'generated mirror\n');
  // generated artifact — excluded
  writeFileSync(join(root, 'docs', 'generated', 'x.md'), '# gen\n');

  const registry = { projects: [{ id, path: root }] };
  return { root, id, registry };
}

console.log('obsidian-export tests\n');

test('visibleExportPath remaps protected lessons out of the dot-folder', () => {
  assert.equal(visibleExportPath('.claude/rules/lessons.md'), 'lessons.md');
  assert.equal(visibleExportPath('docs/specs/auth.md'), 'docs/specs/auth.md');
});

test('exports canonical corpus; excludes generated mirrors + docs/generated', () => {
  const { root, id, registry } = makeVault();
  const before = listFiles(root).filter((f) => !f.startsWith(EXPORT_REL));
  const out = exportObsidianVault({ vaultId: id, registry });
  assert.equal(out.ok, true);

  const exported = out.files;
  assert.ok(exported.includes('docs/specs/auth.md'));
  assert.ok(exported.includes('rules/core.md'));
  assert.ok(exported.includes('memory/note.md'));
  assert.ok(exported.includes('lessons.md'), 'protected lessons remapped visible');
  // generated views + generated artifacts excluded
  assert.ok(!exported.some((f) => f.startsWith('.claude/')));
  assert.ok(!exported.some((f) => f.startsWith('.cursor/')));
  assert.ok(!exported.some((f) => f.includes('generated/')));

  // wikilinks preserved verbatim
  const authAbs = join(out.dest, 'docs/specs/auth.md');
  assert.match(readFileSync(authAbs, 'utf8'), /\[\[core\]\]/);

  // Obsidian config + manifest present
  assert.ok(existsSync(join(out.dest, '.obsidian', 'app.json')));
  assert.ok(existsSync(join(out.dest, 'export-manifest.json')));
  assert.equal(out.writes, 'projection-only');

  // READ-ONLY w.r.t. source: nothing outside the export dir changed/added.
  const after = listFiles(root).filter((f) => !f.startsWith(EXPORT_REL));
  assert.deepEqual(after.sort(), before.sort(), 'source tree must be untouched');
});

test('rebuildable: re-export drops stale files', () => {
  const { root, id, registry } = makeVault();
  const first = exportObsidianVault({ vaultId: id, registry });
  // add a stray file into the export dir, then re-export
  writeFileSync(join(first.dest, 'stray.md'), 'stale\n');
  const second = exportObsidianVault({ vaultId: id, registry });
  assert.equal(existsSync(join(second.dest, 'stray.md')), false, 're-export wipes stale');
  void root;
});

test('requires vaultId', () => {
  assert.throws(() => exportObsidianVault({}), (e) => e && e.code === 'VAULT_ID');
});

process.exit(failed ? 1 : 0);
